from enum import Enum

class States(Enum):
    MAIN_MENU = 1
    CREATE_TASK_NAME = 2
    CREATE_TASK_DESCRIPTION = 3
    CREATE_TASK_OPTIONALS = 4
    CREATE_TASK_CHANGE_NAME = 5
    CREATE_TASK_CHANGE_DESCRIPTION = 6
    CREATE_TASK_CHANGE_ROLES = 7
    CREATE_TASK_CHANGE_ASSIGNEES = 8
    CREATE_TASK_CHANGE_ESTIMATE = 9
    CREATE_TASK_CHANGE_ATTACHMENT = 10
    CREATE_TASK_CHANGE_DUE_DATE = 11
    DEPARTMENT_SELECTION_MENU = 12
    
    EDIT_USER_NAME = 13
    EDIT_USER_SURNAME = 14
    EDIT_USER_MANAGER = 15
    EDIT_USER_PHONE = 16
    EDIT_USER_OPTIONALS = 17
    EDIT_USER_OPTIONALS_USER_SELECTED = 18
    EDIT_USER_PREVIEW = 19

    REPORTING_ISSUE = 20